name: tests
on: [push]
env:
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: lescanotiers
  DB_USERNAME: root
  DB_PASSWORD: root
jobs:
  tests:
    runs-on: ubuntu-20.04
    name: "CI Les Canotiers V2"
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lescanotiers
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      # Setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2, cs2pr
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Start mysql service
        run: sudo systemctl start mysql

      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Preparing environment
      - name: Copy .env file
        run: cp .env.example .env

      - name: Installation du projet (database)
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: |
          composer install
          php artisan key:generate
          php artisan migrate:fresh --seed
          php artisan optimize:clear

      - name: Execute Laravel Pint
        run: composer pint

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "dev@ltiollier.fr"

      - name: commit
        run: |
          git add -u
          (git commit -m ":art: Auto style fix" && git push origin) || true

      - name: Running phpstan
        run: composer run phpstan

      - name: Installation du projet (npm)
        run: |
          yarn
          yarn build

      - name: Running phpunit
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: php artisan test --parallel

      - name: Refresh database
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: php artisan migrate:refresh --seed
